name: yay

on:
  repository_dispatch:
    types: [yay]

env:
  build_prefix: extra-x86_64

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
      - name: Get time
        id: time
        run: echo "::set-output name=time::$(date +%F-%T)"

      - name: Set up cache
        uses: actions/cache@master
        with:
          path: /var/cache/pacman/pkg
          key: pacman-cache-x86_64-${{ steps.time.outputs.time }}
          restore-keys: pacman-cache-x86_64-

      - uses: actions/checkout@master
        with:
          repository: petronny/action-tools
          path: action-tools

      - run: cat ${GITHUB_EVENT_PATH}

      - name: Initialize
        run: ${GITHUB_WORKSPACE}/action-tools/initialize.sh

      - uses: actions/checkout@master

      - name: Pre-build
        run: aur-pre-build.sh

      - name: Build the package
        run: archbuild.sh

      - name: Post-build
        run: aur-post-build.sh

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: '~/packages'

      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: build.log
          path: '~/build.log'
