name: yay

on:
  repository_dispatch:
    types: [yay]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
      - name: Get time
        id: time
        run: echo "::set-output name=time::$(date +%F-%T)"

      - name: Set up cache
        uses: actions/cache@master
        with:
          path: /var/cache/pacman/pkg
          key: pacman-cache-x86_64-${{ steps.time.outputs.time }}
          restore-keys: pacman-cache-x86_64-

      - uses: actions/checkout@master
        with:
          repository: petronny/action-tools
          path: action-tools

      - name: Initialize
        run: |
          actions-tools/initialize.sh

      - uses: actions/checkout@master

      - name: Pre-build
        run: |
          pwd
          ls
          cd ${GITHUB_WORKFLOW}
          aur-pre-build.sh

      - name: Build the package
        run: |
          extra-x86_64-build -- -U pkgbuild 1>"$HOME"/extra-x86_64-build.log 2>&1
          ls -l "$HOME"/{packages,sources,srcpackages,makepkglogs}

      - name: Post-build
        run: |
          clean-up-cache.sh

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: yay
          path: '~/packages/yay-*.pkg.tar.zst'

      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: extra-x86_64-build.log
          path: '~/extra-x86_64-build.log'
